# ===============================
# Aider project configuration
# ===============================

# ---- Choose ONE model ----
# Default: Local Ollama (assumes OLLAMA_API_BASE=http://127.0.0.1:11434)
model: "ollama_chat/qwen3-coder:30b"

# ---- Alternatives (uncomment exactly ONE) ----

# # Remote Ollama:
# # Set OLLAMA_API_BASE to your remote host (e.g., http://100.108.135.106:11434)
# # export OLLAMA_API_BASE="http://<REMOTE_HOST>:11434"
# model: "ollama_chat/qwen3-coder:30b"

# # OpenAI:
# # Requires OPENAI_API_KEY in your environment.
# # export OPENAI_API_KEY="sk-..."
# # Aider will send requests to OpenAI directly.
# # Examples:
# #   - steady/code-friendly: o4-mini
# #   - reasoning: o3-mini
# model: "o4-mini"

# # Claude (Anthropic):
# # Requires ANTHROPIC_API_KEY in your environment.
# # export ANTHROPIC_API_KEY="sk-ant-..."
# # Example “Sonnet” model (good general/code):
# model: "sonnet"

# ------------------------------------------------
# Auto test & lint after each edit (your TODO)
# ------------------------------------------------
auto_test: true
test_cmd: "make -j$(nproc)"

auto_lint: true
lint_cmd: "make lint || true"

# ------------------------------------------------
# Quality-of-life defaults (safe to keep)
# ------------------------------------------------
yes: true # auto-apply patches without prompting
stream: true # stream tokens for a smoother UX

# ------------------------------------------------
# Optional: context limits, if you run into bloat
# ------------------------------------------------
# max_chat_history_tokens: 20000
# max_context_tokens: 200000

# ------------------------------------------------
# Notes
# ------------------------------------------------
# 1) This config is read from the *repo root* you run `aider` in.
# 2) To override the model just for one run:
#      aider --model "ollama_chat/qwen3-coder:30b"
# 3) Provider auth (don’t put keys in this file):
#      export OPENAI_API_KEY=...
#      export ANTHROPIC_API_KEY=...
#      export OLLAMA_API_BASE=http://host:11434
# 4) Keep a .aiderignore to exclude heavy dirs (node_modules, data/, etc.).

