services:
  artificialeconomist-nodejs:
    container_name: artificialeconomist-nodejs
    build:
        context: ./
        dockerfile: ./docker/web/Dockerfile
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - artificialeconomist-mongo
      - artificialeconomist-tensorflow
  artificialeconomist-mongo:
    container_name: artificialeconomist-mongo
    image: mongo:4
    command: mongod --port 27017 --bind_ip 0.0.0.0
    restart: unless-stopped
    volumes:
      - /data/db/artificialeconomist_mongo:/data/db
    expose:
      - '27017'
  artificialeconomist-tensorflow:
    container_name: artificialeconomist-tensorflow
    build:
        context: ./
        dockerfile: ./docker/tf/Dockerfile.cpu
    restart: unless-stopped
    expose:
      - '8008'
    depends_on:
      - artificialeconomist-mongo

