
# Those after 5.1 require AVX. not on old CPU on desktop.
FROM tensorflow/tensorflow:1.15.5-py3
#FROM tensorflow/tensorflow:1.5.1-py3

#RUN rm /etc/apt/sources.list.d/cuda.list /etc/apt/sources.list.d/nvidia-ml.list
RUN apt-get update && apt-get -y install git

RUN \
git clone https://github.com/openai/gpt-2 && \
cd gpt-2 && \
git checkout a74da5d && \
rm -rf .gitignore .gitattributes .git/ && \
cd ..

COPY requirements.txt ./
RUN pip3 install -r requirements.txt

WORKDIR ./gpt-2

COPY new_server.py ./src/
COPY econstormodel/ ./models/econstormodel/

RUN pip3 install -r requirements.txt

CMD [ "python3", "-u", "./src/new_server.py", "0", "artificialeconomist-mongo", "27017", "artificialeconomist-tensorflow", "8008" ]
