#FROM tensorflow/tensorflow-gpu:1.15.5-gpu-py3
FROM tensorflow/tensorflow-gpu:1.5.1-gpu-py3	# Those after 5.1 require AVX. not on old CPU.
RUN rm /etc/apt/sources.list.d/cuda.list /etc/apt/sources.list.d/nvidia-ml.list
RUN apt-get update && apt-get -y install git

RUN \
git clone https://github.com/openai/gpt-2 && \
cd gpt-2 && \
git checkout a74da5d && \
cd ..

WORKDIR ./gpt-2

COPY new_server.py ./src/
COPY econstormodel/ ./models/econstormodel/

RUN pip3 install -r requirements.txt
RUN pip3 install pymongo==3.11.3

CMD [ "python3", "-u", "./src/new_server.py", "1", "artificialeconomist-mongo", "27017", "artificialeconomist-tensorflow", "8008" ]
