FROM tensorflow/tensorflow:1.15.5-py3
RUN apt-get update && apt-get -y install git

RUN git clone https://github.com/openai/gpt-2
WORKDIR ./gpt-2

COPY new_server.py ./src/
COPY econstormodel/ ./models/econstormodel/

RUN pip3 install -r requirements.txt
RUN pip3 install pymongo==3.11.3

RUN python3 --version

CMD [ "python3", "-u", "./src/new_server.py", "0", "artificialeconomist_mongo", "27017", "artificialeconomist_tensorflow", "8008" ]
