
FROM tensorflow/tensorflow-gpu:1.15.5-gpu-py3
RUN rm /etc/apt/sources.list.d/cuda.list /etc/apt/sources.list.d/nvidia-ml.list

RUN apt-get update && apt-get install --no-install-recommends --yes \
  git                                                               \
  && apt-get clean                                                  \
  && rm -rf /var/lib/apt/lists/*                                    \
  && rm -rf /usr/share/doc/* /usr/share/man/*

WORKDIR /app

# Note these are *my* requirements
COPY requirements.txt .
#RUN pip3 install --upgrade pip && pip3 install -r requirements.txt
RUN pip3 install --disable-pip-version-check --no-cache-dir -r requirements.txt

RUN git clone https://github.com/openai/gpt-2
WORKDIR /app/gpt-2
RUN git checkout a74da5d
RUN rm -rf .gitignore .gitattributes .git/

COPY new_server.py ./src/
COPY econstormodel/ ./models/econstormodel/

# Note these are *gpt2* requirements (WORKDIR changed)
#RUN pip3 install --upgrade pip && pip3 install -r requirements.txt
RUN pip3 install --disable-pip-version-check --no-cache-dir -r requirements.txt

CMD [ "python3", "-u", "./src/new_server.py", "1", "artificialeconomist-mongo", "27017", "artificialeconomist-tensorflow", "8008" ]
